# Generated by Django 4.0.3 on 2022-04-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='friends_with_high_gpa',
            field=models.IntegerField(),
        ),
    ]
