# Generated by Django 4.0.3 on 2022-03-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
    ]
