# Generated by Django 4.0.3 on 2022-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_goal_options_remove_goal_complete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['complete']},
        ),
        migrations.AddField(
            model_name='goal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
