# Generated by Django 4.0.3 on 2022-03-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_goal_options_goal_complete_goal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=200)),
                ('practice_test_score', models.IntegerField()),
                ('private_tutor_time', models.IntegerField()),
                ('have_a_strategy', models.BooleanField(default=False)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Gpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type2', models.CharField(max_length=200)),
                ('current_gpa', models.IntegerField()),
                ('library_hours', models.IntegerField()),
                ('friends_with_high_gpa', models.IntegerField()),
                ('office_hours', models.IntegerField()),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
            ],
        ),
    ]
