# Generated by Django 4.0.3 on 2022-03-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sat_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpa',
            old_name='goal_id',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='sat',
            old_name='goal_id',
            new_name='goal',
        ),
    ]
