# Generated by Django 4.0.3 on 2022-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_goal_id_gpa_goal_rename_goal_id_sat_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpa',
            old_name='type2',
            new_name='category_gpa',
        ),
        migrations.RenameField(
            model_name='sat',
            old_name='type1',
            new_name='category_sat',
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
