# Generated by Django 4.0.3 on 2022-03-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_type2_gpa_category_gpa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['completed']},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='complete',
            new_name='completed',
        ),
    ]
