# Generated by Django 4.0.3 on 2022-03-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_goal_options_rename_complete_goal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('SAT', 'Sat'), ('GPA', 'Gpa')], default='GPA', max_length=10),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.goal'),
        ),
        migrations.AlterField(
            model_name='sat',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.goal'),
        ),
    ]
