# Generated by Django 4.0.3 on 2022-03-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_goal_category_alter_gpa_goal_alter_sat_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpa',
            name='category_gpa',
        ),
        migrations.RemoveField(
            model_name='sat',
            name='category_sat',
        ),
    ]
