# Generated by Django 4.0.3 on 2022-03-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_gpa_category_gpa_remove_sat_category_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='current_gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='friends_with_high_gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpa', to='base.goal'),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='library_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='office_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sat',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sat', to='base.goal'),
        ),
        migrations.AlterField(
            model_name='sat',
            name='practice_test_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sat',
            name='private_tutor_time',
            field=models.FloatField(),
        ),
    ]
