# Generated by Django 4.0.3 on 2022-03-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_gpa_category_gpa_remove_sat_category_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('SAT', 'Sat'), ('GPA', 'Gpa')], max_length=10),
        ),
    ]
