# Generated by Django 4.0.3 on 2022-03-30 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpa', to='base.goal'),
        ),
        migrations.AlterField(
            model_name='sat',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sat', to='base.goal'),
        ),
    ]
