# Generated by Django 4.0.3 on 2022-03-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('sat_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('type1', models.CharField(max_length=200)),
                ('practice_test_score', models.IntegerField()),
                ('private_tutor_time', models.IntegerField()),
                ('have_a_strategy', models.BooleanField(default=False)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Gpa',
            fields=[
                ('gpa_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('type2', models.CharField(max_length=200)),
                ('current_gpa', models.IntegerField()),
                ('library_hours', models.IntegerField()),
                ('friends_with_high_gpa', models.IntegerField()),
                ('office_hours', models.IntegerField()),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
            ],
        ),
    ]
